### ISSUE TITLE
Improve error message when `converter` of `mapParsers` throws

### ISSUE THREAD

**Issue by arseniiv** [renatoathaydes/parcey#7] opened 2016-04-09 14:05 UTC
If `converter` of `mapValueParser` throws, reported error message confusingly states that the problem is in the last parser applied, when, however, error is kind of meta-level. For example, parsing `"a"` with following:

``` ceylon
value parser = mapParsers {
    parsers = {
        character('a')
    };
    function converter(Anything parsed) {
        assert (0 == 1);
        return parsed;
    }
};
```

returns an error stating `'a'` doesn’t match against `'a'`, when in fact it matched early.
Maybe throwable’s `description` and `mapValueParser` returned parser’s `name` should be returned?

**Comment by renatoathaydes** [comment] 2016-04-10 19:44
I'm working on this... looks like the problem goes a bit deeper than just the `map*` parsers...

**Comment by renatoathaydes** [comment] 2016-04-16 21:40
Closing this as duplicate of #4 .

**Closed as completed by renatoathaydes** 2016-04-16 21:40 UTC
